server:
  host: '*'
  port: 5432

log: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  topic: !Env XTDB_LOG_TOPIC

storage: !Local
  path: "/var/lib/xtdb/buffers"

healthz:
  host: '*'
  port: 8080

modules: 
- !HttpServer
  host: '*'
  port: 3000


