server:
  host: '*'
  port: 5432

log: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  topic: !Env XTDB_LOG_TOPIC

storage: !Remote
  objectStore: !GoogleCloud
    projectId: !Env XTDB_GCP_PROJECT_ID
    bucket: !Env XTDB_GCP_BUCKET
    prefix: "xtdb-object-store"

diskCache:
  path: !Env XTDB_GCP_LOCAL_DISK_CACHE_PATH

healthz:
  host: '*'
  port: 8080

modules:
- !HttpServer
  host: '*'
  port: 3000
