server:
  host: '*'
  port: 5432

log: !Local
  path: "/var/lib/xtdb/log"

storage: !Local
  path: "/var/lib/xtdb/buffers"

healthz:
  host: '*'
  port: 8080

modules: 
- !HttpServer
  host: '*'
  port: 3000
